# Generated by Django 5.2 on 2025-04-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rating_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
